name: AlexFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 2.2
description: Plugin for the AlexFreedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials, DisguiseCraft, BarAPI, CoreProtect]
authors: [Madgeek1450, DarthSalamon, Camzie99, RobinGall2910, tylerhyperHD]

# plugin.yml is no longer used to define commands.
